import { Response } from "express"
import PDFDocument from "pdfkit"
import ExcelJS from "exceljs"
import { AuthRequest } from "../middleware/auth"
import { prisma } from "../db"

// Helper to format date
const formatDate = (date: Date | string) => {
    return new Date(date).toLocaleDateString()
}

// Export Purchases to PDF
export const exportPurchasesPDF = async (req: AuthRequest, res: Response) => {
    try {
        const user = req.user!
        const { baseId, fromDate, toDate } = req.query

        const where: any = {}
        if (user.role !== "ADMIN") {
            where.baseId = user.baseId
        } else if (baseId) {
            where.baseId = baseId as string
        }

        if (fromDate || toDate) {
            where.date = {}
            if (fromDate) where.date.gte = fromDate as string
            if (toDate) where.date.lte = toDate as string
        }

        const purchases = await prisma.purchase.findMany({
            where,
            include: {
                base: true,
                equipment: true,
                user: true,
            },
            orderBy: { date: "desc" },
        })

        const doc = new PDFDocument({ margin: 50 })

        // Set response headers
        res.setHeader("Content-Type", "application/pdf")
        res.setHeader("Content-Disposition", "attachment; filename=purchases_report.pdf")

        doc.pipe(res)

        // Header
        doc.fontSize(20).text("Military Asset Management System", { align: "center" })
        doc.fontSize(16).text("Purchases Report", { align: "center" })
        doc.moveDown()
        doc.fontSize(10).text(`Generated on: ${new Date().toLocaleString()}`, { align: "right" })
        doc.text(`Generated by: ${user.email}`, { align: "right" })
        doc.moveDown()

        // Table Header
        const tableTop = 150
        doc.fontSize(10).font("Helvetica-Bold")
        doc.text("Date", 50, tableTop)
        doc.text("Equipment", 120, tableTop)
        doc.text("Quantity", 250, tableTop)
        doc.text("Base", 320, tableTop)
        doc.text("User", 450, tableTop)

        doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke()

        // Table Rows
        let y = tableTop + 25
        doc.font("Helvetica")

        purchases.forEach((p) => {
            if (y > 700) {
                doc.addPage()
                y = 50
            }
            doc.text(formatDate(p.date), 50, y)
            doc.text(p.equipment.name, 120, y)
            doc.text(p.quantity.toString(), 250, y)
            doc.text(p.base.name, 320, y)
            doc.text(p.user.email, 450, y, { width: 100 })
            y += 20
        })

        doc.end()
    } catch (error) {
        console.error("PDF Export Error:", error)
        res.status(500).json({ error: "Failed to generate PDF report" })
    }
}

// Export Transfers to Excel
export const exportTransfersExcel = async (req: AuthRequest, res: Response) => {
    try {
        const user = req.user!
        const { baseId, fromDate, toDate } = req.query

        const where: any = {}
        if (user.role !== "ADMIN") {
            where.OR = [
                { fromBaseId: user.baseId },
                { toBaseId: user.baseId }
            ]
        } else if (baseId) {
            where.OR = [
                { fromBaseId: baseId as string },
                { toBaseId: baseId as string }
            ]
        }

        if (fromDate || toDate) {
            where.date = {}
            if (fromDate) where.date.gte = fromDate as string
            if (toDate) where.date.lte = toDate as string
        }

        const transfers = await prisma.transfer.findMany({
            where,
            include: {
                fromBase: true,
                toBase: true,
                equipment: true,
            },
            orderBy: { date: "desc" },
        })

        const workbook = new ExcelJS.Workbook()
        const worksheet = workbook.addWorksheet("Transfers")

        worksheet.columns = [
            { header: "Date", key: "date", width: 15 },
            { header: "Equipment", key: "equipment", width: 20 },
            { header: "Quantity", key: "quantity", width: 10 },
            { header: "From Base", key: "fromBase", width: 20 },
            { header: "To Base", key: "toBase", width: 20 },
            { header: "Status", key: "status", width: 15 },
        ]

        transfers.forEach((t) => {
            worksheet.addRow({
                date: formatDate(t.date),
                equipment: t.equipment.name,
                quantity: t.quantity,
                fromBase: t.fromBase.name,
                toBase: t.toBase.name,
                status: t.status,
            })
        })

        // Style header
        worksheet.getRow(1).font = { bold: true }

        res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        res.setHeader("Content-Disposition", "attachment; filename=transfers_report.xlsx")

        await workbook.xlsx.write(res)
        res.end()
    } catch (error) {
        console.error("Excel Export Error:", error)
        res.status(500).json({ error: "Failed to generate Excel report" })
    }
}

// Export Assignments to PDF
export const exportAssignmentsPDF = async (req: AuthRequest, res: Response) => {
    try {
        const user = req.user!
        const { baseId, fromDate, toDate } = req.query

        const where: any = {}
        if (user.role !== "ADMIN") {
            where.baseId = user.baseId
        } else if (baseId) {
            where.baseId = baseId as string
        }

        if (fromDate || toDate) {
            where.date = {}
            if (fromDate) where.date.gte = fromDate as string
            if (toDate) where.date.lte = toDate as string
        }

        const assignments = await prisma.assignment.findMany({
            where,
            include: {
                base: true,
                equipment: true,
                user: true,
            },
            orderBy: { date: "desc" },
        })

        const doc = new PDFDocument({ margin: 50 })

        res.setHeader("Content-Type", "application/pdf")
        res.setHeader("Content-Disposition", "attachment; filename=assignments_report.pdf")

        doc.pipe(res)

        doc.fontSize(20).text("Military Asset Management System", { align: "center" })
        doc.fontSize(16).text("Assignments & Expenditures Report", { align: "center" })
        doc.moveDown()
        doc.fontSize(10).text(`Generated on: ${new Date().toLocaleString()}`, { align: "right" })
        doc.moveDown()

        const tableTop = 150
        doc.fontSize(10).font("Helvetica-Bold")
        doc.text("Date", 50, tableTop)
        doc.text("Type", 110, tableTop)
        doc.text("Equipment", 180, tableTop)
        doc.text("Qty", 280, tableTop)
        doc.text("Personnel/Reason", 320, tableTop)
        doc.text("Base", 480, tableTop)

        doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke()

        let y = tableTop + 25
        doc.font("Helvetica")

        assignments.forEach((a: any) => {
            if (y > 700) {
                doc.addPage()
                y = 50
            }
            doc.text(formatDate(a.date), 50, y)
            doc.text(a.type, 110, y)
            doc.text(a.equipment.name, 180, y)
            doc.text(a.quantity.toString(), 280, y)
            doc.text(a.personnelName || a.reason || "—", 320, y, { width: 150 })
            doc.text(a.base?.name || "—", 480, y)
            y += 20
        })

        doc.end()
    } catch (error) {
        console.error("PDF Export Error:", error)
        res.status(500).json({ error: "Failed to generate PDF report" })
    }
}
